#    Filters are most commonly used for
#    -Authentication
#    -Logging
#    -Serving static content
#    -Dynamic routing based on some conditions (A/B testing)

#zuul:
#  routes:
#    get:
#      path: /get/**
#      url: http://httpbin.org/get
#    links:
#      path: /links/**
#      url: http://httpbin.org/links
#    images:
#      path: /image/**
#      url: http://httpbin.org/image

zuul:
#  prefix: /api
  routes:
    test:
      path: /redirect/**
      url: http://google.com
#      http://localhost:8765/movie-service10/movies/1
    movie-service10: /movies/**
#      path: /movies/**
#      serviceId: MOVIE-SERVICE4
#      url: http://localhost:2222
    recomendations-service: /recomendations/**
#      path: /recomendations/**
#      url: http://localhost:3333
#      serviceId: RECOMENDATION-SERVICE2
    user-service: /api/user/**
    auth-server : /auth/**

---
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: edge-server


---
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
---
oauth:
  client-secret: trusted-app:secret
  token-path: /auth/oauth/token
  refresh-token:
    max-age: 2592000 # 30 days
    cookie-name: refresh_token
  access-token:
    max-age: 86400 # 1 day
    cookie-name: access_token

